# This workflow will release and publish the project with Maven
# It uses Maven release to release the process including deploy.
# Deployment is done to GitHub Package registry.

name: Maven Release

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  release:
    name: Maven Release
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets. GH_RELEASE_TOKEN }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[
        { "id": "github", "name": "GitHub zetool Apache Maven Packages", "url": "https://maven.pkg.github.com/zetool/network-flow" }
        ]'
        servers: '[{ "id": "github", "username": "zetool-bot", "password": "${GITHUB_TOKEN}" }]'
    - name: Build with Maven
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: mvn -B package --file pom.xml
    - name: Copy settings for release
      run: cp ~/.m2/settings.xml .
    - name: Publish to GitHub Packages
      uses: kappmeier/github-actions-maven-release@master
      with:
        release-branch-name: "master"

        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.GH_GPG_KEY_ID }}
        gpg-key: ${{ secrets. GH_GPG_KEY }}

        settings-file: "./settings.xml"

        maven-args: "-X -Dmaven.javadoc.skip=true -DskipTests"

        git-release-bot-name: "zetool-bot"
        git-release-bot-email: "github@zetool.org"

        access-token: ${{ secrets.GH_RELEASE_TOKEN }}
